### PR TITLE
Update jdbc_overrides.rb

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
Same as #4

### CODE REVIEW

**Comment by headius** [comment]
Ping @enebo @rdubya is this good to go?

**Comment by rdubya** [comment]
Sorry, I'm crazy busy right now. I need to get the tests running again but I'm wondering what made this start happening since I'm fairly certain that call was required to get tests to pass previously. Is it using a newer version of the mssql driver or something?

**Comment by HarlemSquirrel** [comment]
@headius @rdubya @enebo is there any way I can help test this out to move a release along? Thanks!

**Comment by rdubya** [comment]
Sorry, I haven't had any time to look at this. Is this happening because of a newer version of the mssql driver or something?

**Comment by rdubya** [comment]
Just realized that I still haven't gotten a 5.2 compatible version released yet :( so this PR doesn't matter as much as  #4 I'd like to know why it suddenly broke though, should we be limiting the versions of the mssql driver that we are compatible with?

**Comment by HarlemSquirrel** [comment]
I wish I had more knowledge of mssql. We have one database and we use two tables so it's light.

**Comment by HarlemSquirrel** [comment]
For what it's worth, I've been using this driver from my branch with rails 5.2 in production for a few months now with no problem. Just one model and table on that app.

**Comment by rdubya** [comment]
We're implementing a change to deal with the JDBC driver include as mentioned here: https://github.com/jruby/activerecord-jdbcsqlserver-adapter/pull/4

So I'm going to close this PR. Thank you for bringing it to our attention and putting in the effort to find a solution.

**Pull request closed without merging**
